version: 2

sources:
  - name: snowflake_desafioNW
    database: FEA24_9
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: person
        data_tests:
          - unique
          - not_null

      - name: address
        data_tests:
          - unique
          - not_null
     
      - name: stateprovince
        data_tests:
          - unique
          - not_null

      - name: countryregion
        data_tests:
          - unique
          - not_null
          