version: 2

sources:
  - name: snowflake_desafioNW
    database: FEA24_9
    schema: RAW_ADVENTURE_WORKS
    tables:
      
      - name: person
        data_tests:
          - unique
          - not_null

      - name: address
        data_tests:
              - unique
              - not_null
     
      - name: stateprovince
        data_tests:
          - unique
          - not_null

      - name: countryregion
        data_tests:
          - unique
          - not_null
      
      - name: CREDITCARD
        data_tests:
          - unique
          - not_null


      - name: CUSTOMER
        data_tests:
          - unique
          - not_null

      
      - name: PRODUCT
        data_tests:
          - unique
          - not_null
         
      - name: PRODUCTCATEGORY
        data_tests:
          - unique
          - not_null
      
      - name: PRODUCTSUBCATEGORY
        data_tests:
          - unique
          - not_null
      
          
      - name: SALESORDERDETAIL
        data_tests:
          - unique
          - not_null

                
      - name: SALESORDERHEADER
        data_tests:
          - unique
          - not_null
                    
      - name: SALESORDERHEADERSALESREASON
        data_tests:
          - unique
          - not_null

      
      - name: SALESREASON
        data_tests:
          - unique
          - not_null

      - name: seed






      
      